---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_centos7:
  - name: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-7"
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-7') }}"
  - name: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Debug-7"
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Debug-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-Debug-7') }}"
  - name: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-Testing-7"
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Testing-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-Testing-7') }}"


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-CentOS-7"
  download_policy: "{{ foreman_products_defaults_download_policy_centos7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7 | bool }}"


foreman_products_centos7:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Base"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-base"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/os/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Updates"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-updates"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/updates/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Extras"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-extras"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/extras/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Plus"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-plus"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/centosplus/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - fasttrack"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-fasttrack"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/fasttrack/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"

      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - cr"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-cr"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/cr/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"

      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 LTS Kernels for x86_64"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-kernel"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_altarch }}/7/kernel/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 Experimental Kernels for x86_64"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-kernel-experimental"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_altarch }}/7/experimental/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"

foreman_products_centos7_kickstart:
  - name: "{{ foreman_product_name_prefix | default('') }}CentOS"
    label: "{{ foreman_product_label_prefix | default('') }}CentOS"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Base"
        label: "{{ foreman_repo_label_prefix | default('') }}centos-7-base"
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/7.9.2009/os/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"


foreman_content_views_centos7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_base"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Base"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_updates"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Updates"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_extras"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Extras"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_plus"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - Plus"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_fasttrack"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - fasttrack"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_cr"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 - cr"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_kernel"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 LTS Kernels for x86_64"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_kernel_experimental"
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}CentOS 7 Experimental Kernels for x86_64"
        product: "{{ foreman_product_name_prefix | default('') }}CentOS"
    allow_promote: "{{ foreman_cv_allow_promote_centos7 }}"

foreman_composite_content_views_centos7:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}centos7"
    organization: "{{ foreman_organization_centos7 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_centos7 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_centos7 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_base"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_updates"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_plus"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_fasttrack"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_cr"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_kernel"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}centos7_kernel_experimental"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_centos7:
  - name: "CentOS"
    major: "7"
    minor: "0.1406"
    description: "CentOS Linux release 7.0.1406 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "1.1503"
    description: "CentOS Linux release 7.1.1503 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "2.1511"
    description: "CentOS Linux release 7.2.1511 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "3.1611"
    description: "CentOS Linux release 7.3.1611 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "4.1708"
    description: "CentOS Linux release 7.4.1708 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "5.1804"
    description: "CentOS Linux release 7.5.1804"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "6.1810"
    description: "CentOS Linux release 7.6.1810 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "7.1908"
    description: "CentOS Linux release 7.7.1908 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "8.2003"
    description: "CentOS Linux release 7.8.2003 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: "9.2009"
    description: "CentO Linux releaseS 7.9.2009 (Core)"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "CentOS"
    major: "7"
    minor: ""
    description: "CentOS 7"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_centos7:
  - name: "{{ foreman_media_name_prefix | default('') }}CentOS 7"
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 7


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "CentOS"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard


foreman_activation_keys_centos7:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}centos7"
    organization: "{{ foreman_organization_centos7 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}centos7"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-base"
        override: enabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-updates"
        override: enabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-extras"
        override: enabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-plus"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-fasttrack"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-cr"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-kernel"
        override: disabled
      - label: "{{ foreman_organization }}_{{ foreman_product_label_prefix | default('') }}CentOS_{{ foreman_repo_label_prefix | default('') }}centos-7-kernel-experimental"
        override: disabled


foreman_sync_plan_products_centos7: []

